comments:  # 评论
    enable: true  # 开启评论
    type: disqus  # 指定使用的评论模块  available: disqus | valine | gitalk | utterances | changyan | livere 

    #---------------------------
# 评论
# Comments
#---------------------------
# Disqus
disqus:
  enable: true
  shortname: s81679 # your shortname
  count: true